baseURL = "openflowlabs.com"
DefaultContentLanguage = "en"
title = "OpenFlowLabs"
theme = "ofl"

[params]
    description = "OpenFlowLabs, we create the invisible technology that makes everything work."
    linkedin = "https://www.linkedin.com/company/open-flow-labs/"

[languages]
    [languages.en]
        languageCode = "en-us"
        languageName = "English"
        weight = 1
    [languages.en.menu]
        [[languages.en.menu.main]]
            url    = "/articles"
            name   = "Articles"
            weight = 1
    [languages.de]
        languageCode = "de-ch"
        languageName = "Deutsch"
        weight = 1
        [languages.de.menu]
            [[languages.de.menu.main]]
                url    = "/de/articles"
                name   = "Blog"
                weight = 1