baseURL = "https://openflowlabs.github.io/"
languageCode = "de-ch"
title = "OpenFlowLabs GmbH"
theme = "syna"
name = "OpenFlowLabs"

[minify]
    disableSVG = true

[params]
    [params.colors]
        danger = "#ff7149"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "images/logo-no-text-favicon.ico"
    favicon_ico_sizes = "32x32"
    favicon_png = "images/logo-no-text-favicon.png"
    favicon_svg = "images/logo-no-text.svg"