baseURL = "https://openflowlabs.github.io/"
languageCode = "de-ch"
title = "OpenFlowLabs GmbH"
theme = "syna"
name = "OpenFlowLabs"

[minify]
    disableSVG = true

[params]
    [params.colors]
        danger = "#ff7149"